### ISSUE TITLE
Cannot npm install @imaginary-dev/nextjs-util

### ISSUE THREAD

**Issue by kitajchuk** [imaginary-dev/imaginary-dev#36]
This package appears to be unpublished, however it is referenced in your README's and documentation for use with Next.js applications. Are there plans to publish this?

Error on install:

```
$ npm install @imaginary-dev/nextjs-util
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@imaginary-dev%2fnextjs-util - Not found
npm ERR! 404
npm ERR! 404  '@imaginary-dev/nextjs-util@*' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
...
```

**Comment by aickin** [comment]
Yikes, how embarrassing!

The next.js integration is very, very new, and I just forgot to publish the library. I've done that now, and I've also tested out the install directions in a clean project (which I should have done already, I apologize!).

Thanks so much for the report, and again: apologies!

**Comment by kitajchuk** [comment]
> Yikes, how embarrassing!
> 
> The next.js integration is very, very new, and I just forgot to publish the library. I've done that now, and I've also tested out the install directions in a clean project (which I should have done already, I apologize!).
> 
> Thanks so much for the report, and again: apologies!

No worries at all! I just watched a Loom video I saw on HN and got excited because I have some next projects this would be very useful for. Thanks for the quick resolution. Stoked to try this out 🤘

**Comment by kitajchuk** [comment]
> > Yikes, how embarrassing!
> > The next.js integration is very, very new, and I just forgot to publish the library. I've done that now, and I've also tested out the install directions in a clean project (which I should have done already, I apologize!).
> > Thanks so much for the report, and again: apologies!
> 
> No worries at all! I just watched a Loom video I saw on HN and got excited because I have some next projects this would be very useful for. Thanks for the quick resolution. Stoked to try this out 🤘

Quick follow up: how far out are you from supporting swc for next apps?

**Comment by aickin** [comment]
Thanks for the grace, and please let us know what feedback you have: good, bad, or ugly.

> Quick follow up: how far out are you from supporting swc for next apps?

It's on the list for sure, but priority depends on what users care most about. Right now we are focused on a VSCode plugin to test imaginary functions in IDE.

**Comment by kitajchuk** [comment]
> Yikes, how embarrassing!
> 
> The next.js integration is very, very new, and I just forgot to publish the library. I've done that now, and I've also tested out the install directions in a clean project (which I should have done already, I apologize!).
> 
> Thanks so much for the report, and again: apologies!

Hey, I don't mean to be annoying but I'm still not seeing that package as available. I've tried both yarn/npm and I still get the error on install and don't see it on the registry...Any help would be much appreciated.

<img width="1792" alt="Screen Shot 2023-03-30 at 4 10 54 PM" src="https://user-images.githubusercontent.com/438711/228984667-8239e240-d85f-4585-b9c7-e3c6ab351e7c.png">

**Comment by aickin** [comment]
Oh geez, I published it and ran through the install instructions on a clean next-js project, and it all worked.

But...

The package was private to our org, and my npm client was logged in as me. <facepalm>

Should be fixed now. Thanks for your patience!

**Comment by kitajchuk** [comment]
> 

Okay, cool. Got this working on a project. I could not get it to work with a non TS API file—maybe that isn't supported? All the docs show TS examples so I tried it and it worked. Frontend is still plain JS.

One thing to note is it seems the consumer type definitions aren't reflective of what I can actually import and use in my API file.

<img width="902" alt="Screen Shot 2023-03-30 at 4 46 47 PM" src="https://user-images.githubusercontent.com/438711/228989062-98875c66-503b-43e0-a791-ac10607e442f.png">

The `makeImaginaryNextFunction` isn't recognized and the `server` TS definitions define unavailable exports `makeNextjsHandler` and `makeNextjsMultiHandler`.

**Comment by kitajchuk** [comment]
I'm also getting the occasional failure of this nature basically using the blog post title example on an existing project of German => English translations. I'm creating a plain text payload from the English to send to the backend function. Possibly something is amiss in the text string but haven't found what it is yet...

<img width="1792" alt="Screen Shot 2023-03-30 at 5 01 00 PM" src="https://user-images.githubusercontent.com/438711/228990608-30174178-df0c-41f3-979f-c068c22bacea.png">
